apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-thirdparty-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi